// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense() {
  return window['go']['app']['App']['ActivateLicense']();
}

export function ApplyFilter(arg1, arg2) {
  return window['go']['app']['App']['ApplyFilter'](arg1, arg2);
}

export function ApplyFormula(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyFormula'](arg1, arg2, arg3);
}

export function ApproveUndoActions(arg1) {
  return window['go']['app']['App']['ApproveUndoActions'](arg1);
}

export function AutoFitColumns(arg1, arg2) {
  return window['go']['app']['App']['AutoFitColumns'](arg1, arg2);
}

export function CancelChat() {
  return window['go']['app']['App']['CancelChat']();
}

export function CheckLicense() {
  return window['go']['app']['App']['CheckLicense']();
}

export function ClearChat() {
  return window['go']['app']['App']['ClearChat']();
}

export function ClearFilters(arg1) {
  return window['go']['app']['App']['ClearFilters'](arg1);
}

export function ClearLastBatchID() {
  return window['go']['app']['App']['ClearLastBatchID']();
}

export function ClearRange(arg1, arg2) {
  return window['go']['app']['App']['ClearRange'](arg1, arg2);
}

export function ConfigurePivotFields(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ConfigurePivotFields'](arg1, arg2, arg3, arg4);
}

export function ConfirmPendingAction() {
  return window['go']['app']['App']['ConfirmPendingAction']();
}

export function ConnectExcel() {
  return window['go']['app']['App']['ConnectExcel']();
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function CopyRange(arg1, arg2, arg3) {
  return window['go']['app']['App']['CopyRange'](arg1, arg2, arg3);
}

export function CreateChart(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateChart'](arg1, arg2, arg3, arg4);
}

export function CreateNewSheet(arg1) {
  return window['go']['app']['App']['CreateNewSheet'](arg1);
}

export function CreateNewWorkbook() {
  return window['go']['app']['App']['CreateNewWorkbook']();
}

export function CreatePivotTable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreatePivotTable'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTable'](arg1, arg2, arg3, arg4);
}

export function DeleteChartByName(arg1, arg2) {
  return window['go']['app']['App']['DeleteChartByName'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function DeleteLastMessages(arg1) {
  return window['go']['app']['App']['DeleteLastMessages'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteRows'](arg1, arg2, arg3);
}

export function DeleteSheet(arg1) {
  return window['go']['app']['App']['DeleteSheet'](arg1);
}

export function DeleteTable(arg1, arg2) {
  return window['go']['app']['App']['DeleteTable'](arg1, arg2);
}

export function EndUndoBatch() {
  return window['go']['app']['App']['EndUndoBatch']();
}

export function FormatRange(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['FormatRange'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetActiveSelection() {
  return window['go']['app']['App']['GetActiveSelection']();
}

export function GetAskBeforeApply() {
  return window['go']['app']['App']['GetAskBeforeApply']();
}

export function GetAvailableModels(arg1, arg2) {
  return window['go']['app']['App']['GetAvailableModels'](arg1, arg2);
}

export function GetChatHistory() {
  return window['go']['app']['App']['GetChatHistory']();
}

export function GetCurrentConversationID() {
  return window['go']['app']['App']['GetCurrentConversationID']();
}

export function GetHeaders(arg1, arg2) {
  return window['go']['app']['App']['GetHeaders'](arg1, arg2);
}

export function GetLastBatchID() {
  return window['go']['app']['App']['GetLastBatchID']();
}

export function GetLicenseMessage() {
  return window['go']['app']['App']['GetLicenseMessage']();
}

export function GetLicenseStatus() {
  return window['go']['app']['App']['GetLicenseStatus']();
}

export function GetPreviewData(arg1, arg2) {
  return window['go']['app']['App']['GetPreviewData'](arg1, arg2);
}

export function GetSavedConfig() {
  return window['go']['app']['App']['GetSavedConfig']();
}

export function GetUsedRange(arg1) {
  return window['go']['app']['App']['GetUsedRange'](arg1);
}

export function HasPendingAction() {
  return window['go']['app']['App']['HasPendingAction']();
}

export function HasPendingUndoActionsForConversation(arg1) {
  return window['go']['app']['App']['HasPendingUndoActionsForConversation'](arg1);
}

export function InsertRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['InsertRows'](arg1, arg2, arg3);
}

export function IsLicenseValid() {
  return window['go']['app']['App']['IsLicenseValid']();
}

export function ListCharts(arg1) {
  return window['go']['app']['App']['ListCharts'](arg1);
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function ListPivotTables(arg1) {
  return window['go']['app']['App']['ListPivotTables'](arg1);
}

export function ListSheets() {
  return window['go']['app']['App']['ListSheets']();
}

export function ListTables(arg1) {
  return window['go']['app']['App']['ListTables'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['app']['App']['LoadConversation'](arg1);
}

export function MergeCells(arg1, arg2) {
  return window['go']['app']['App']['MergeCells'](arg1, arg2);
}

export function NewConversation() {
  return window['go']['app']['App']['NewConversation']();
}

export function QueryExcel(arg1, arg2) {
  return window['go']['app']['App']['QueryExcel'](arg1, arg2);
}

export function RefreshWorkbooks() {
  return window['go']['app']['App']['RefreshWorkbooks']();
}

export function RejectPendingAction() {
  return window['go']['app']['App']['RejectPendingAction']();
}

export function RenameSheet(arg1, arg2) {
  return window['go']['app']['App']['RenameSheet'](arg1, arg2);
}

export function SendErrorFeedback(arg1) {
  return window['go']['app']['App']['SendErrorFeedback'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['app']['App']['SetAPIKey'](arg1);
}

export function SetAskBeforeApply(arg1) {
  return window['go']['app']['App']['SetAskBeforeApply'](arg1);
}

export function SetBorders(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBorders'](arg1, arg2, arg3);
}

export function SetColumnWidth(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetColumnWidth'](arg1, arg2, arg3);
}

export function SetConversationIDForUndo(arg1) {
  return window['go']['app']['App']['SetConversationIDForUndo'](arg1);
}

export function SetExcelContext(arg1, arg2) {
  return window['go']['app']['App']['SetExcelContext'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['app']['App']['SetModel'](arg1);
}

export function SetRowHeight(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetRowHeight'](arg1, arg2, arg3);
}

export function SheetExists(arg1) {
  return window['go']['app']['App']['SheetExists'](arg1);
}

export function SortRange(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SortRange'](arg1, arg2, arg3, arg4);
}

export function StartUndoBatch() {
  return window['go']['app']['App']['StartUndoBatch']();
}

export function StartWorkbookWatcher() {
  return window['go']['app']['App']['StartWorkbookWatcher']();
}

export function StopWorkbookWatcher() {
  return window['go']['app']['App']['StopWorkbookWatcher']();
}

export function SwitchProvider(arg1) {
  return window['go']['app']['App']['SwitchProvider'](arg1);
}

export function UndoByConversation(arg1) {
  return window['go']['app']['App']['UndoByConversation'](arg1);
}

export function UndoLastChange() {
  return window['go']['app']['App']['UndoLastChange']();
}

export function UnmergeCells(arg1, arg2) {
  return window['go']['app']['App']['UnmergeCells'](arg1, arg2);
}

export function UpdateConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['UpdateConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateExcelCell(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateExcelCell'](arg1, arg2, arg3, arg4);
}

export function WriteToExcel(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteToExcel'](arg1, arg2, arg3);
}
