// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFormula(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyFormula'](arg1, arg2, arg3);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function ConnectExcel() {
  return window['go']['main']['App']['ConnectExcel']();
}

export function CreateChart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChart'](arg1, arg2, arg3, arg4);
}

export function CreateNewSheet(arg1) {
  return window['go']['main']['App']['CreateNewSheet'](arg1);
}

export function CreateNewWorkbook() {
  return window['go']['main']['App']['CreateNewWorkbook']();
}

export function CreatePivotTable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePivotTable'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteLastMessages(arg1) {
  return window['go']['main']['App']['DeleteLastMessages'](arg1);
}

export function EndUndoBatch() {
  return window['go']['main']['App']['EndUndoBatch']();
}

export function GetActiveSelection() {
  return window['go']['main']['App']['GetActiveSelection']();
}

export function GetAvailableModels(arg1, arg2) {
  return window['go']['main']['App']['GetAvailableModels'](arg1, arg2);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetPreviewData(arg1, arg2) {
  return window['go']['main']['App']['GetPreviewData'](arg1, arg2);
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function LoadConversation(arg1) {
  return window['go']['main']['App']['LoadConversation'](arg1);
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function RefreshWorkbooks() {
  return window['go']['main']['App']['RefreshWorkbooks']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetExcelContext(arg1, arg2) {
  return window['go']['main']['App']['SetExcelContext'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function StartUndoBatch() {
  return window['go']['main']['App']['StartUndoBatch']();
}

export function UndoLastChange() {
  return window['go']['main']['App']['UndoLastChange']();
}

export function UpdateConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateExcelCell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateExcelCell'](arg1, arg2, arg3, arg4);
}

export function WriteToExcel(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteToExcel'](arg1, arg2, arg3);
}
