// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {excel} from '../models';
import {storage} from '../models';
import {main} from '../models';

export function ApplyFilter(arg1:string,arg2:string):Promise<void>;

export function ApplyFormula(arg1:number,arg2:number,arg3:string):Promise<void>;

export function AutoFitColumns(arg1:string,arg2:string):Promise<void>;

export function CancelChat():Promise<void>;

export function ClearChat():Promise<void>;

export function ClearFilters(arg1:string):Promise<void>;

export function ClearRange(arg1:string,arg2:string):Promise<void>;

export function ConfigurePivotFields(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<Record<string, string>>):Promise<void>;

export function ConnectExcel():Promise<dto.ExcelStatus>;

export function CopyRange(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateChart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateNewSheet(arg1:string):Promise<void>;

export function CreateNewWorkbook():Promise<string>;

export function CreatePivotTable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteChartByName(arg1:string,arg2:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteLastMessages(arg1:number):Promise<void>;

export function DeleteRows(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DeleteSheet(arg1:string):Promise<void>;

export function DeleteTable(arg1:string,arg2:string):Promise<void>;

export function EndUndoBatch():Promise<void>;

export function FormatRange(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:number,arg6:string,arg7:string):Promise<void>;

export function GetActiveSelection():Promise<excel.SheetData>;

export function GetAvailableModels(arg1:string,arg2:string):Promise<Array<dto.ModelInfo>>;

export function GetChatHistory():Promise<Array<dto.ChatMessage>>;

export function GetHeaders(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPreviewData(arg1:string,arg2:string):Promise<dto.PreviewData>;

export function GetSavedConfig():Promise<storage.Config>;

export function GetUsedRange(arg1:string):Promise<string>;

export function InsertRows(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ListCharts(arg1:string):Promise<Array<string>>;

export function ListConversations():Promise<Array<dto.ConversationInfo>>;

export function ListPivotTables(arg1:string):Promise<Array<string>>;

export function ListSheets():Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<string>>;

export function LoadConversation(arg1:string):Promise<Array<dto.ChatMessage>>;

export function MergeCells(arg1:string,arg2:string):Promise<void>;

export function NewConversation():Promise<string>;

export function QueryExcel(arg1:string,arg2:Record<string, string>):Promise<main.QueryResult>;

export function RefreshWorkbooks():Promise<dto.ExcelStatus>;

export function RenameSheet(arg1:string,arg2:string):Promise<void>;

export function SendErrorFeedback(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetBorders(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetColumnWidth(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetExcelContext(arg1:string,arg2:string):Promise<string>;

export function SetModel(arg1:string):Promise<void>;

export function SetRowHeight(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SheetExists(arg1:string):Promise<boolean>;

export function SortRange(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function StartUndoBatch():Promise<void>;

export function SwitchProvider(arg1:string):Promise<storage.Config>;

export function UndoLastChange():Promise<void>;

export function UnmergeCells(arg1:string,arg2:string):Promise<void>;

export function UpdateConfig(arg1:number,arg2:number,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateExcelCell(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WriteToExcel(arg1:number,arg2:number,arg3:string):Promise<void>;
