// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFilter(arg1, arg2) {
  return window['go']['main']['App']['ApplyFilter'](arg1, arg2);
}

export function ApplyFormula(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyFormula'](arg1, arg2, arg3);
}

export function AutoFitColumns(arg1, arg2) {
  return window['go']['main']['App']['AutoFitColumns'](arg1, arg2);
}

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function ClearFilters(arg1) {
  return window['go']['main']['App']['ClearFilters'](arg1);
}

export function ClearRange(arg1, arg2) {
  return window['go']['main']['App']['ClearRange'](arg1, arg2);
}

export function ConfigurePivotFields(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfigurePivotFields'](arg1, arg2, arg3, arg4);
}

export function ConnectExcel() {
  return window['go']['main']['App']['ConnectExcel']();
}

export function CopyRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyRange'](arg1, arg2, arg3);
}

export function CreateChart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChart'](arg1, arg2, arg3, arg4);
}

export function CreateNewSheet(arg1) {
  return window['go']['main']['App']['CreateNewSheet'](arg1);
}

export function CreateNewWorkbook() {
  return window['go']['main']['App']['CreateNewWorkbook']();
}

export function CreatePivotTable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePivotTable'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2, arg3, arg4);
}

export function DeleteChartByName(arg1, arg2) {
  return window['go']['main']['App']['DeleteChartByName'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteLastMessages(arg1) {
  return window['go']['main']['App']['DeleteLastMessages'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRows'](arg1, arg2, arg3);
}

export function DeleteSheet(arg1) {
  return window['go']['main']['App']['DeleteSheet'](arg1);
}

export function DeleteTable(arg1, arg2) {
  return window['go']['main']['App']['DeleteTable'](arg1, arg2);
}

export function EndUndoBatch() {
  return window['go']['main']['App']['EndUndoBatch']();
}

export function FormatRange(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['FormatRange'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetActiveSelection() {
  return window['go']['main']['App']['GetActiveSelection']();
}

export function GetAvailableModels(arg1, arg2) {
  return window['go']['main']['App']['GetAvailableModels'](arg1, arg2);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetHeaders(arg1, arg2) {
  return window['go']['main']['App']['GetHeaders'](arg1, arg2);
}

export function GetPreviewData(arg1, arg2) {
  return window['go']['main']['App']['GetPreviewData'](arg1, arg2);
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function GetUsedRange(arg1) {
  return window['go']['main']['App']['GetUsedRange'](arg1);
}

export function InsertRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRows'](arg1, arg2, arg3);
}

export function ListCharts(arg1) {
  return window['go']['main']['App']['ListCharts'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListPivotTables(arg1) {
  return window['go']['main']['App']['ListPivotTables'](arg1);
}

export function ListSheets() {
  return window['go']['main']['App']['ListSheets']();
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['main']['App']['LoadConversation'](arg1);
}

export function MergeCells(arg1, arg2) {
  return window['go']['main']['App']['MergeCells'](arg1, arg2);
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function QueryExcel(arg1, arg2) {
  return window['go']['main']['App']['QueryExcel'](arg1, arg2);
}

export function RefreshWorkbooks() {
  return window['go']['main']['App']['RefreshWorkbooks']();
}

export function RenameSheet(arg1, arg2) {
  return window['go']['main']['App']['RenameSheet'](arg1, arg2);
}

export function SendErrorFeedback(arg1) {
  return window['go']['main']['App']['SendErrorFeedback'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetBorders(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBorders'](arg1, arg2, arg3);
}

export function SetColumnWidth(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetColumnWidth'](arg1, arg2, arg3);
}

export function SetExcelContext(arg1, arg2) {
  return window['go']['main']['App']['SetExcelContext'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetRowHeight(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRowHeight'](arg1, arg2, arg3);
}

export function SheetExists(arg1) {
  return window['go']['main']['App']['SheetExists'](arg1);
}

export function SortRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SortRange'](arg1, arg2, arg3, arg4);
}

export function StartUndoBatch() {
  return window['go']['main']['App']['StartUndoBatch']();
}

export function StartWorkbookWatcher() {
  return window['go']['main']['App']['StartWorkbookWatcher']();
}

export function StopWorkbookWatcher() {
  return window['go']['main']['App']['StopWorkbookWatcher']();
}

export function SwitchProvider(arg1) {
  return window['go']['main']['App']['SwitchProvider'](arg1);
}

export function UndoLastChange() {
  return window['go']['main']['App']['UndoLastChange']();
}

export function UnmergeCells(arg1, arg2) {
  return window['go']['main']['App']['UnmergeCells'](arg1, arg2);
}

export function UpdateConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateExcelCell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateExcelCell'](arg1, arg2, arg3, arg4);
}

export function WriteToExcel(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteToExcel'](arg1, arg2, arg3);
}
