// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {excel} from '../models';
import {storage} from '../models';

export function ApplyFormula(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ClearChat():Promise<void>;

export function ConnectExcel():Promise<dto.ExcelStatus>;

export function CreateChart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateNewSheet(arg1:string):Promise<void>;

export function CreateNewWorkbook():Promise<string>;

export function CreatePivotTable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteLastMessages(arg1:number):Promise<void>;

export function EndUndoBatch():Promise<void>;

export function GetActiveSelection():Promise<excel.SheetData>;

export function GetAvailableModels(arg1:string,arg2:string):Promise<Array<dto.ModelInfo>>;

export function GetChatHistory():Promise<Array<dto.ChatMessage>>;

export function GetPreviewData(arg1:string,arg2:string):Promise<dto.PreviewData>;

export function GetSavedConfig():Promise<storage.Config>;

export function ListConversations():Promise<Array<dto.ConversationInfo>>;

export function LoadConversation(arg1:string):Promise<Array<dto.ChatMessage>>;

export function NewConversation():Promise<string>;

export function RefreshWorkbooks():Promise<dto.ExcelStatus>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetExcelContext(arg1:string,arg2:string):Promise<string>;

export function SetModel(arg1:string):Promise<void>;

export function StartUndoBatch():Promise<void>;

export function UndoLastChange():Promise<void>;

export function UpdateConfig(arg1:number,arg2:number,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateExcelCell(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WriteToExcel(arg1:number,arg2:number,arg3:string):Promise<void>;
